name: Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew health:build

      - name: Publish Library
        run: |
          echo "Publishing and Releasing $GITHUB_REF_NAME"
          ./gradlew health:publish -Pversion=$GITHUB_REF_NAME
          echo "Published and Released $GITHUB_REF_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $GITHUB_REF_NAME
          release_name: "Release $GITHUB_REF_NAME"
          draft: false
          prerelease: false
